sudo: false
language: node_js
node_js:
- 15
cache: npm
branches:
  only:
  - src
script:
- yuque-hexo clean
- yuque-hexo sync
- hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  target-brach: master
  on:
    branch: src
  local-dir: public
notifications:
  email:
  - biaogejiushibiao@qq.com
  on_success: never
  on_failure: always
