name: BLOG-CICD
on:
  push:
    branches: [ src ]
  pull_request:
    branches: [ src ]
  workflow_dispatch:
jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install yuque-hexo -g
          npm install
          yuque-hexo sync
      - name: Generate files
        run: hexo generate

      - name: Deploy blog
        run: |
          git clone "https://${{ secrets.GH_REF }}" deploy_git
          mv ./deploy_git/.git ./public/
          cd ./public
          git config user.name "mikeygithub"
          git config user.email "biaogejiushibiao@outlook.com"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          echo "finish commit"
          git remote set-url origin git@github.com:mikeygithub/mikeygithub.github.io.git
          git push --force --quiet "https://${{ secrets.GH_TOKEN }}@${{ secrets.GH_REF }}" master:master
          git push -u origin master
